import { afterEach, describe, expect, it } from 'vitest';
import { hashPasswordWithSalt, verifyPassword } from '@/adapters/crypto-adapter';

const originalCrypto = globalThis.crypto;

afterEach(() => {
  Object.defineProperty(globalThis, 'crypto', {
    configurable: true,
    value: originalCrypto,
  });
});

describe('password hash compatibility', () => {
  it('should verify password generated by hashPasswordWithSalt', async () => {
    const password = 'issue27-test-password';
    const hash = await hashPasswordWithSalt(password);

    await expect(verifyPassword(password, hash)).resolves.toBe(true);
  });

  it('should reject wrong password for generated hash', async () => {
    const hash = await hashPasswordWithSalt('correct-password');

    await expect(verifyPassword('wrong-password', hash)).resolves.toBe(false);
  });

  it('should still use pbkdf2 hashing when crypto.subtle is unavailable', async () => {
    Object.defineProperty(globalThis, 'crypto', {
      configurable: true,
      value: {
        getRandomValues<T extends ArrayBufferView>(array: T): T {
          const view = new Uint8Array(array.buffer, array.byteOffset, array.byteLength);
          for (let i = 0; i < view.length; i++) {
            view[i] = (i * 17 + 11) % 256;
          }
          return array;
        },
      },
    });

    const password = 'mobile-fallback-password';
    const hash = await hashPasswordWithSalt(password);

    expect(hash.startsWith('$pbkdf2$')).toBe(true);
    await expect(verifyPassword(password, hash)).resolves.toBe(true);
    await expect(verifyPassword('bad-password', hash)).resolves.toBe(false);
  }, 20000);

  it('should reject legacy fallback hash scheme', async () => {
    const legacyHash = '$fallback$c2FsdA==$deadbeefcafebabe';
    await expect(verifyPassword('any-password', legacyHash)).resolves.toBe(false);
  });
});
