name = "exomind"
compatibility_date = "2025-02-27"
compatibility_flags = ["nodejs_compat"]

main = "./website/dist/_worker.js/index.js"

[assets]
directory = "./website/dist"

# R2 bucket for build artifacts (release & preview channels)
[[r2_buckets]]
binding = "R2"
bucket_name = "exomind-releases"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1