name = "exomind"
compatibility_date = "2025-02-27"

main = "./website/dist/_worker.js/index.js"

[assets]
directory = "./website/dist"
exclude = ["_worker.js"]

# R2 bucket for build artifacts (release & preview channels)
[[r2_buckets]]
binding = "R2"
bucket_name = "exomind-releases"
