import { mkdtemp, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe, expect, it } from 'vitest';
import {
  applyCanonicalVersionToTexts,
  bumpCanonicalVersion,
  findLatestCanonicalTag,
  resolveCanonicalVersionFromTexts,
  resolveReleaseVersionPlan,
  writeCanonicalVersion,
} from '../../../scripts/dev/release-version-lib.ts';

describe('release-version-lib', () => {
  it('finds the latest canonical tag from mixed tag namespaces（应忽略非 canonical tag 并按语义化版本取最新）', () => {
    const result = findLatestCanonicalTag([
      'release/v0.3.5',
      'build/v0.3.6-build.68',
      'v0.4.2',
      'v0.4.4',
      'v0.4.3',
    ]);

    expect(result).toBe('v0.4.4');
  });

  it('bumps only when local version is already synced to the latest remote version（本地必须先与远端最新版本对齐后才能自动 bump）', () => {
    const plan = resolveReleaseVersionPlan({
      localVersion: '0.4.4',
      remoteTags: ['v0.4.4', 'v0.4.2'],
      bump: 'patch',
    });

    expect(plan.baseVersion).toBe('0.4.4');
    expect(plan.nextVersion).toBe('0.4.5');
    expect(plan.nextTag).toBe('v0.4.5');
  });

  it('rejects bump planning when local version is not the latest remote version（本地版本落后或超前远端最新版本时应直接拒绝）', () => {
    expect(() =>
      resolveReleaseVersionPlan({
        localVersion: '0.4.3',
        remoteTags: ['v0.4.4', 'v0.4.2'],
        bump: 'patch',
      }),
    ).toThrow(/本地版本 0.4.3 与远端最新版本 0.4.4 不一致/);
  });

  it('accepts an explicit version only when it is newer than the base（显式版本必须大于基线版本）', () => {
    const plan = resolveReleaseVersionPlan({
      localVersion: '0.4.4',
      remoteTags: ['v0.4.4'],
      bump: 'patch',
      explicitVersion: '0.4.6',
    });

    expect(plan.nextVersion).toBe('0.4.6');
  });

  it('rejects explicit versions that do not advance（显式版本不允许原地重复）', () => {
    expect(() =>
      resolveReleaseVersionPlan({
        localVersion: '0.4.4',
        remoteTags: ['v0.4.4'],
        bump: 'patch',
        explicitVersion: '0.4.4',
      }),
    ).toThrow(/下一版本必须大于基线版本/);
  });

  it('updates all canonical version files consistently（应同时更新三处 canonical version 文件）', () => {
    const updated = applyCanonicalVersionToTexts(
      {
        packageJson: JSON.stringify({ name: 'exomind', version: '0.4.4' }, null, 2),
        cargoToml: ['[package]', 'name = "exomind"', 'version = "0.4.4"', ''].join('\n'),
        tauriConfig: JSON.stringify({ productName: 'ExoMind', version: '0.4.4' }, null, 2),
      },
      '0.4.5',
    );

    expect(resolveCanonicalVersionFromTexts(updated)).toBe('0.4.5');
    expect(updated.packageJson).toContain('"version": "0.4.5"');
    expect(updated.cargoToml).toContain('version = "0.4.5"');
    expect(updated.tauriConfig).toContain('"version": "0.4.5"');
  });

  it('bumps semantic versions by major minor and patch（应支持 major/minor/patch bump）', () => {
    expect(bumpCanonicalVersion('0.4.4', 'patch')).toBe('0.4.5');
    expect(bumpCanonicalVersion('0.4.4', 'minor')).toBe('0.5.0');
    expect(bumpCanonicalVersion('0.4.4', 'major')).toBe('1.0.0');
  });

  it('writes Cargo.lock root package version when the lockfile exists（存在 Cargo.lock 时应同步根包版本）', async () => {
    const projectRoot = await mkdtemp(join(tmpdir(), 'release-version-lib-'));

    try {
      await mkdir(join(projectRoot, 'src-tauri'), { recursive: true });
      await writeFile(
        join(projectRoot, 'package.json'),
        JSON.stringify({ name: 'exomind', version: '0.4.4' }, null, 2),
      );
      await writeFile(
        join(projectRoot, 'src-tauri', 'Cargo.toml'),
        ['[package]', 'name = "exomind"', 'version = "0.4.4"', ''].join('\n'),
      );
      await writeFile(
        join(projectRoot, 'src-tauri', 'tauri.conf.json'),
        JSON.stringify({ productName: 'ExoMind', version: '0.4.4' }, null, 2),
      );
      await writeFile(
        join(projectRoot, 'Cargo.lock'),
        [
          '# This file is automatically @generated by Cargo.',
          'version = 4',
          '',
          '[[package]]',
          'name = "exomind"',
          'version = "0.4.4"',
          '',
          '[[package]]',
          'name = "serde"',
          'version = "1.0.0"',
          '',
        ].join('\n'),
      );

      await writeCanonicalVersion('0.4.5', projectRoot);

      const cargoLock = await readFile(join(projectRoot, 'Cargo.lock'), 'utf8');
      expect(cargoLock).toContain('name = "exomind"\nversion = "0.4.5"');
      expect(cargoLock).not.toContain('name = "exomind"\nversion = "0.4.4"');
    } finally {
      await rm(projectRoot, { recursive: true, force: true });
    }
  });

  it('does not partially rewrite version files when Cargo.lock sync fails（Cargo.lock 同步失败时不应留下半更新文件）', async () => {
    const projectRoot = await mkdtemp(join(tmpdir(), 'release-version-lib-'));

    try {
      await mkdir(join(projectRoot, 'src-tauri'), { recursive: true });
      await writeFile(
        join(projectRoot, 'package.json'),
        JSON.stringify({ name: 'exomind', version: '0.4.4' }, null, 2),
      );
      await writeFile(
        join(projectRoot, 'src-tauri', 'Cargo.toml'),
        ['[package]', 'name = "exomind"', 'version = "0.4.4"', ''].join('\n'),
      );
      await writeFile(
        join(projectRoot, 'src-tauri', 'tauri.conf.json'),
        JSON.stringify({ productName: 'ExoMind', version: '0.4.4' }, null, 2),
      );
      await writeFile(
        join(projectRoot, 'Cargo.lock'),
        [
          '# This file is automatically @generated by Cargo.',
          'version = 4',
          '',
          '[[package]]',
          'name = "serde"',
          'version = "1.0.0"',
          '',
        ].join('\n'),
      );

      await expect(writeCanonicalVersion('0.4.5', projectRoot)).rejects.toThrow(
        /未找到 Cargo\.lock 中 exomind 对应的根 package 版本块/,
      );

      expect(await readFile(join(projectRoot, 'package.json'), 'utf8')).toContain(
        '"version": "0.4.4"',
      );
      expect(
        await readFile(join(projectRoot, 'src-tauri', 'Cargo.toml'), 'utf8'),
      ).toContain('version = "0.4.4"');
      expect(
        await readFile(join(projectRoot, 'src-tauri', 'tauri.conf.json'), 'utf8'),
      ).toContain('"version": "0.4.4"');
    } finally {
      await rm(projectRoot, { recursive: true, force: true });
    }
  });
});
