import {
  buildRuntimeAuthHeaders,
  getSelectedRuntimeTarget,
  type RuntimeTarget,
} from "@/config/runtime-target";
import type {
  ITaskPort,
  CreateTaskInput,
  UpdateTaskInput,
} from "@/lib/environment/interfaces/task.port";
import type {
  Dependency,
  LegacyTaskStatus,
  TaskNode,
  TaskNodeLike,
  TaskStatus,
  TaskStatusTransition,
  TaskTransitionReason,
} from "@/lib/types/task";
import { canTransition, normalizeTaskNode } from "@/lib/types/task";
import {
  ensureRuntimeResponseOk,
  fetchRuntimeResponseOrThrow,
} from "@/lib/utils/runtime-request-error";
import { appendRuntimeProfileScope } from "./runtime-profile-scope";

type RuntimeFetch = typeof fetch;

export interface RuntimeTaskDependencyPayload {
  task_id: string;
  type: "soft" | "hard";
}

export interface RuntimeTaskStatusTransitionPayload {
  id: string;
  at: number;
  from_status?: TaskStatus | LegacyTaskStatus | null;
  to_status: TaskStatus | LegacyTaskStatus;
  reason: TaskTransitionReason;
  actor_id?: string | null;
  source_host_id?: string | null;
  operation_id?: string | null;
  related_time_block_id?: string | null;
  related_time_block_transition_ref?: string | null;
  auto_generated?: boolean | null;
}

export interface RuntimeTaskPayload {
  id: string;
  title: string;
  description?: string | null;
  done_condition?: string | null;
  status: TaskStatus | LegacyTaskStatus;
  priority: "low" | "medium" | "high";
  tags?: string[];
  source?: string | null;
  parent_id?: string | null;
  depends_on?: RuntimeTaskDependencyPayload[];
  due_at?: number | null;
  estimated_minutes?: number | null;
  time_block_ids?: string[];
  status_transitions?: RuntimeTaskStatusTransitionPayload[];
  created_at: number;
  updated_at: number;
  completed_at?: number | null;
}

export interface TaskRtAdapterOptions {
  fetchImpl?: RuntimeFetch;
  resolveTarget?: () => RuntimeTarget;
}

const ALL_STATUSES: TaskStatus[] = [
  "pending",
  "in_progress",
  "suspended",
  "completed",
  "cancelled",
];

function formatHostForUrl(host: string): string {
  if (host.includes(":") && !host.startsWith("[")) {
    return `[${host}]`;
  }
  return host;
}

function buildBaseUrl(target: RuntimeTarget): string {
  return `http://${formatHostForUrl(target.host)}:${target.port}`;
}

function toRuntimeDependency(
  dependency: Dependency,
): RuntimeTaskDependencyPayload {
  return {
    task_id: dependency.taskId,
    type: dependency.type,
  };
}

function toRuntimeStatusTransition(
  transition: TaskStatusTransition,
): RuntimeTaskStatusTransitionPayload {
  return {
    id: transition.id,
    at: transition.at,
    from_status: transition.fromStatus,
    to_status: transition.toStatus,
    reason: transition.reason,
    actor_id: transition.actorId ?? null,
    source_host_id: transition.sourceHostId ?? null,
    operation_id: transition.operationId ?? null,
    related_time_block_id: transition.relatedTimeBlockId ?? null,
    related_time_block_transition_ref:
      transition.relatedTimeBlockTransitionRef ?? null,
    auto_generated: transition.autoGenerated ?? null,
  };
}

export function runtimeTaskPayloadToTaskNode(
  task: RuntimeTaskPayload,
): TaskNode {
  return normalizeTaskNode({
    id: task.id,
    title: task.title,
    description: task.description ?? undefined,
    doneCondition: task.done_condition ?? undefined,
    status: task.status,
    priority: task.priority,
    dueAt: task.due_at ?? undefined,
    source: task.source ?? undefined,
    parentId: task.parent_id ?? undefined,
    dependsOn: (task.depends_on ?? []).map((dependency) => ({
      taskId: dependency.task_id,
      type: dependency.type,
    })),
    tags: task.tags ?? [],
    estimatedMinutes: task.estimated_minutes ?? undefined,
    timeBlockIds: task.time_block_ids ?? [],
    statusTransitions: (task.status_transitions ?? []).map((transition) => ({
      id: transition.id,
      at: transition.at,
      fromStatus: transition.from_status ?? null,
      toStatus: transition.to_status,
      reason: transition.reason,
      actorId: transition.actor_id ?? undefined,
      sourceHostId: transition.source_host_id ?? undefined,
      operationId: transition.operation_id ?? undefined,
      relatedTimeBlockId: transition.related_time_block_id ?? undefined,
      relatedTimeBlockTransitionRef:
        transition.related_time_block_transition_ref ?? undefined,
      autoGenerated: transition.auto_generated ?? undefined,
    })),
    createdAt: task.created_at,
    updatedAt: task.updated_at,
    completedAt: task.completed_at ?? undefined,
  } satisfies TaskNodeLike);
}

function toRuntimeCreatePayload(
  input: CreateTaskInput,
): Record<string, unknown> {
  return {
    title: input.title,
    ...(input.description !== undefined
      ? { description: input.description }
      : {}),
    ...(input.doneCondition !== undefined
      ? { done_condition: input.doneCondition }
      : {}),
    ...(input.priority !== undefined ? { priority: input.priority } : {}),
    ...(input.dueAt !== undefined ? { due_at: input.dueAt } : {}),
    ...(input.source !== undefined ? { source: input.source } : {}),
    ...(input.parentId !== undefined ? { parent_id: input.parentId } : {}),
    ...(input.tags !== undefined ? { tags: input.tags } : {}),
    ...(input.estimatedMinutes !== undefined
      ? { estimated_minutes: input.estimatedMinutes }
      : {}),
    depends_on: [],
    time_block_ids: [],
  };
}

function toRuntimeUpdatePayload(
  input: UpdateTaskInput,
): Record<string, unknown> {
  // Use `'key' in input` to detect explicitly provided fields (including undefined).
  // When a field is explicitly set to undefined, send `null` so the backend clears it.
  return {
    ...("title" in input ? { title: input.title } : {}),
    ...("description" in input
      ? { description: input.description ?? null }
      : {}),
    ...("doneCondition" in input
      ? { done_condition: input.doneCondition ?? null }
      : {}),
    ...("priority" in input ? { priority: input.priority } : {}),
    ...("dueAt" in input ? { due_at: input.dueAt ?? null } : {}),
    ...("source" in input ? { source: input.source ?? null } : {}),
    ...("parentId" in input ? { parent_id: input.parentId ?? null } : {}),
    ...("dependsOn" in input && input.dependsOn
      ? { depends_on: input.dependsOn.map(toRuntimeDependency) }
      : {}),
    ...("tags" in input ? { tags: input.tags } : {}),
    ...("estimatedMinutes" in input
      ? { estimated_minutes: input.estimatedMinutes ?? null }
      : {}),
    ...("timeBlockIds" in input ? { time_block_ids: input.timeBlockIds } : {}),
  };
}

export class TaskRtAdapter implements ITaskPort {
  private readonly fetchImpl: RuntimeFetch;
  private readonly resolveTarget: () => RuntimeTarget;

  constructor(options: TaskRtAdapterOptions = {}) {
    this.fetchImpl =
      options.fetchImpl ?? ((input, init) => globalThis.fetch(input, init));
    this.resolveTarget =
      options.resolveTarget ?? (() => getSelectedRuntimeTarget());
  }

  async listTasks(includeCancelled = false): Promise<TaskNode[]> {
    const tasks = await this.requestJson<RuntimeTaskPayload[]>("/tasks");
    const mapped = tasks.map(runtimeTaskPayloadToTaskNode);
    return includeCancelled
      ? mapped
      : mapped.filter((task) => task.status !== "cancelled");
  }

  async getTaskById(id: string): Promise<TaskNode | null> {
    const target = this.resolveTarget();
    const url = this.url(`/tasks/${encodeURIComponent(id)}`, target);
    const response = await fetchRuntimeResponseOrThrow(
      this.fetchImpl,
      url,
      {
        method: "GET",
        headers: buildRuntimeAuthHeaders(target, {
          Accept: "application/json",
        }),
      },
      "RT get task",
    );
    if (response.status === 404) {
      return null;
    }
    await ensureRuntimeResponseOk(response, url, "RT get task");
    return runtimeTaskPayloadToTaskNode(
      (await response.json()) as RuntimeTaskPayload,
    );
  }

  async createTask(input: CreateTaskInput): Promise<TaskNode> {
    const task = await this.requestJson<RuntimeTaskPayload>("/tasks", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Accept: "application/json",
      },
      body: JSON.stringify(toRuntimeCreatePayload(input)),
    });
    return runtimeTaskPayloadToTaskNode(task);
  }

  async updateTask(
    id: string,
    input: UpdateTaskInput,
  ): Promise<TaskNode | null> {
    const target = this.resolveTarget();
    const url = this.url(`/tasks/${encodeURIComponent(id)}`, target);
    const response = await fetchRuntimeResponseOrThrow(
      this.fetchImpl,
      url,
      {
        method: "PUT",
        headers: buildRuntimeAuthHeaders(target, {
          "Content-Type": "application/json",
          Accept: "application/json",
        }),
        body: JSON.stringify(toRuntimeUpdatePayload(input)),
      },
      "RT update task",
    );
    if (response.status === 404) {
      return null;
    }
    await ensureRuntimeResponseOk(response, url, "RT update task");
    return runtimeTaskPayloadToTaskNode(
      (await response.json()) as RuntimeTaskPayload,
    );
  }

  async cancelTask(id: string): Promise<TaskNode | null> {
    const target = this.resolveTarget();
    const url = this.url(`/tasks/${encodeURIComponent(id)}/cancel`, target);
    const response = await fetchRuntimeResponseOrThrow(
      this.fetchImpl,
      url,
      {
        method: "POST",
        headers: buildRuntimeAuthHeaders(target, {
          Accept: "application/json",
        }),
      },
      "RT cancel task",
    );
    if (response.status === 404) {
      return null;
    }
    await ensureRuntimeResponseOk(response, url, "RT cancel task");
    return runtimeTaskPayloadToTaskNode(
      (await response.json()) as RuntimeTaskPayload,
    );
  }

  async transitionTask(id: string, to: TaskStatus): Promise<TaskNode | null> {
    const target = this.resolveTarget();
    const url = this.url(`/tasks/${encodeURIComponent(id)}/transition`, target);
    const response = await fetchRuntimeResponseOrThrow(
      this.fetchImpl,
      url,
      {
        method: "POST",
        headers: buildRuntimeAuthHeaders(target, {
          "Content-Type": "application/json",
          Accept: "application/json",
        }),
        body: JSON.stringify({ status: to }),
      },
      "RT transition task",
    );
    if (response.status === 404) {
      return null;
    }
    await ensureRuntimeResponseOk(response, url, "RT transition task");
    return runtimeTaskPayloadToTaskNode(
      (await response.json()) as RuntimeTaskPayload,
    );
  }

  async getAvailableTransitions(id: string): Promise<TaskStatus[]> {
    const task = await this.getTaskById(id);
    if (!task) {
      return [];
    }
    return ALL_STATUSES.filter((status) => canTransition(task.status, status));
  }

  async applyReplicationSnapshot(
    task: TaskNode,
    sourceHostId?: string,
  ): Promise<"inserted" | "updated" | "ignored"> {
    const target = this.resolveTarget();
    const url = this.url("/tasks/replication/upsert", target);
    const response = await fetchRuntimeResponseOrThrow(
      this.fetchImpl,
      url,
      {
        method: "POST",
        headers: buildRuntimeAuthHeaders(target, {
          "Content-Type": "application/json",
          Accept: "application/json",
        }),
        body: JSON.stringify({
          task: {
            id: task.id,
            title: task.title,
            description: task.description ?? null,
            done_condition: task.doneCondition ?? null,
            status: task.status,
            priority: task.priority,
            tags: task.tags,
            source: task.source ?? null,
            parent_id: task.parentId ?? null,
            depends_on: task.dependsOn.map(toRuntimeDependency),
            due_at: task.dueAt ?? null,
            estimated_minutes: task.estimatedMinutes ?? null,
            time_block_ids: task.timeBlockIds ?? [],
            status_transitions: (task.statusTransitions ?? []).map(
              toRuntimeStatusTransition,
            ),
            created_at: task.createdAt,
            updated_at: task.updatedAt,
            completed_at: task.completedAt ?? null,
          },
          source_host_id: sourceHostId,
        }),
      },
      "RT task replication upsert",
    );
    await ensureRuntimeResponseOk(response, url, "RT task replication upsert");

    const payload = (await response.json()) as {
      status?: "inserted" | "updated" | "ignored";
    };
    return payload.status ?? "ignored";
  }

  private async requestJson<T>(path: string, init?: RequestInit): Promise<T> {
    const target = this.resolveTarget();
    const url = this.url(path, target);
    const response = await fetchRuntimeResponseOrThrow(this.fetchImpl, url, {
      ...init,
      headers: buildRuntimeAuthHeaders(target, {
        Accept: "application/json",
        ...(init?.headers ?? {}),
      }),
    }, "RT request");
    await ensureRuntimeResponseOk(response, url, "RT request");
    return response.json() as Promise<T>;
  }

  private baseUrl(target = this.resolveTarget()): string {
    return buildBaseUrl(target);
  }

  private url(path: string, target = this.resolveTarget()): string {
    return `${this.baseUrl(target)}${appendRuntimeProfileScope(path)}`;
  }
}
