import { describe, expect, it } from 'vitest';
import { hashPasswordWithSalt, verifyPassword } from '@/adapters/crypto-adapter';

describe('crypto password hash/verify', () => {
  it('verifies password generated by hashPasswordWithSalt', async () => {
    const password = 'password123';
    const storedHash = await hashPasswordWithSalt(password);

    expect(storedHash.startsWith('$pbkdf2$')).toBe(true);
    await expect(verifyPassword(password, storedHash)).resolves.toBe(true);
    await expect(verifyPassword('wrong-password', storedHash)).resolves.toBe(false);
  });

  it('supports hash string without leading $ for compatibility', async () => {
    const password = 'compatible-password';
    const storedHash = await hashPasswordWithSalt(password);
    const legacyHash = storedHash.slice(1);

    await expect(verifyPassword(password, legacyHash)).resolves.toBe(true);
  });
});

