import { TaskRtAdapter } from "@/lib/adapters/task-rt-adapter";
import { getCurrentProfileOrLegacyId } from "@/lib/profile/profile-storage";
import {
  normalizeTaskNode,
  type TaskNode,
  type TaskNodeLike,
} from "@/lib/types/task";

export const TASK_REPLICATION_UPSERTED_TOPIC = "task.replication.upserted";

export interface TaskReplicationCursor {
  kind: "task_snapshot";
  taskId: string;
  updatedAt: number;
  originHostId?: string;
}

export interface TaskReplicationUpsertedPayload {
  schemaVersion: 1;
  scopeKey?: string;
  cursor: TaskReplicationCursor;
  task: TaskNode | RuntimeTaskReplicationPayload;
}

interface RuntimeTaskReplicationPayload {
  id: string;
  title: string;
  description?: string | null;
  status: TaskNode["status"];
  priority: TaskNode["priority"];
  tags?: string[];
  depends_on?: Array<{
    task_id: string;
    type: "soft" | "hard";
  }>;
  time_block_ids?: string[];
  status_transitions?: Array<{
    id: string;
    at: number;
    from_status?: TaskNode["status"] | null;
    to_status: TaskNode["status"];
    reason:
      | "task.create"
      | "task.transition"
      | "timeblock.pause"
      | "timeblock.resume"
      | "timeblock.end";
    actor_id?: string | null;
    source_host_id?: string | null;
    operation_id?: string | null;
    related_time_block_id?: string | null;
    related_time_block_transition_ref?: string | null;
    auto_generated?: boolean | null;
  }>;
  created_at: number;
  updated_at: number;
  completed_at?: number | null;
}

function normalizeReplicatedTask(
  task: TaskNode | RuntimeTaskReplicationPayload,
): TaskNode {
  if ("dependsOn" in task || "createdAt" in task || "updatedAt" in task) {
    return normalizeTaskNode(task as TaskNodeLike);
  }

  return normalizeTaskNode({
    id: task.id,
    title: task.title,
    description: task.description ?? undefined,
    status: task.status,
    priority: task.priority,
    tags: task.tags ?? [],
    dependsOn: (task.depends_on ?? []).map((dependency) => ({
      taskId: dependency.task_id,
      type: dependency.type,
    })),
    timeBlockIds: task.time_block_ids ?? [],
    statusTransitions: (task.status_transitions ?? []).map((transition) => ({
      id: transition.id,
      at: transition.at,
      fromStatus: transition.from_status ?? null,
      toStatus: transition.to_status,
      reason: transition.reason,
      actorId: transition.actor_id ?? undefined,
      sourceHostId: transition.source_host_id ?? undefined,
      operationId: transition.operation_id ?? undefined,
      relatedTimeBlockId: transition.related_time_block_id ?? undefined,
      relatedTimeBlockTransitionRef:
        transition.related_time_block_transition_ref ?? undefined,
      autoGenerated: transition.auto_generated ?? undefined,
    })),
    createdAt: task.created_at,
    updatedAt: task.updated_at,
    completedAt: task.completed_at ?? undefined,
  } satisfies TaskNodeLike);
}

export type ProjectReplicatedTaskResult = "inserted" | "updated" | "ignored";

export async function projectTaskReplicationUpsert(
  payload: TaskReplicationUpsertedPayload,
  userId?: string,
): Promise<ProjectReplicatedTaskResult> {
  const currentScopeKey = userId ?? getCurrentProfileOrLegacyId();
  if (
    typeof payload.scopeKey === "string" &&
    payload.scopeKey.length > 0 &&
    payload.scopeKey !== currentScopeKey
  ) {
    return "ignored";
  }

  const adapter = new TaskRtAdapter();
  return adapter.applyReplicationSnapshot(
    normalizeReplicatedTask(payload.task),
    payload.cursor.originHostId,
  );
}
