import { createUuidV4 } from "@/lib/utils/uuid";

export interface Dependency {
  taskId: string;
  type: "soft" | "hard";
}

/** 5 状态机：pending → in_progress ⇌ suspended → completed / cancelled */
export type TaskStatus =
  | "pending"
  | "in_progress"
  | "suspended"
  | "completed"
  | "cancelled";
export type LegacyTaskStatus = "not_started" | "abandoned";
export type CompatibleTaskStatus = TaskStatus | LegacyTaskStatus;
export type TaskTransitionReason =
  | "task.create"
  | "task.transition"
  | "timeblock.pause"
  | "timeblock.resume"
  | "timeblock.end";

export type TaskPriority = "low" | "medium" | "high";

export interface TaskStatusTransition {
  id: string;
  at: number;
  fromStatus: TaskStatus | null;
  toStatus: TaskStatus;
  reason: TaskTransitionReason;
  actorId?: string;
  sourceHostId?: string;
  operationId?: string;
  relatedTimeBlockId?: string;
  relatedTimeBlockTransitionRef?: string;
  autoGenerated?: boolean;
}

export type TaskStatusTransitionLike = Omit<
  TaskStatusTransition,
  "fromStatus" | "toStatus"
> & {
  fromStatus?: CompatibleTaskStatus | null;
  toStatus: CompatibleTaskStatus;
};

export interface TaskNode {
  id: string;
  title: string;
  description?: string;
  doneCondition?: string; // DOD 完成条件
  status: TaskStatus;
  priority: TaskPriority;
  dueAt?: number; // 截止时间（UTC timestamp，毫秒）
  source?: string; // 来源标识
  parentId?: string; // 父任务 ID（单父，允许为空=根节点）
  dependsOn: Dependency[]; // 依赖关系列表
  tags: string[];
  estimatedMinutes?: number;
  timeBlockIds?: string[]; // Phase4: 历史关联时间块 ID 列表（1:N，曾在任意时段关联过即成立）
  statusTransitions?: TaskStatusTransition[];
  createdAt: number; // UTC timestamp，毫秒
  updatedAt: number;
  completedAt?: number;
}

export type TaskNodeLike = Omit<TaskNode, "status" | "statusTransitions"> & {
  status: CompatibleTaskStatus;
  statusTransitions?: TaskStatusTransitionLike[];
};

export function normalizeTaskStatus(status: CompatibleTaskStatus): TaskStatus {
  switch (status) {
    case "not_started":
      return "pending";
    case "abandoned":
      return "cancelled";
    default:
      return status;
  }
}

export function toStoredTaskStatus(status: TaskStatus): CompatibleTaskStatus {
  // Stage-2: Persist canonical wire format to storage.
  // Legacy values are still accepted via `normalizeTaskStatus()` for backward compatibility.
  return status;
}

export function normalizeTaskStatusTransition(
  transition: TaskStatusTransitionLike,
): TaskStatusTransition {
  return {
    ...transition,
    fromStatus:
      transition.fromStatus == null
        ? null
        : normalizeTaskStatus(transition.fromStatus),
    toStatus: normalizeTaskStatus(transition.toStatus),
  };
}

export function normalizeTaskStatusTransitions(
  transitions?: TaskStatusTransitionLike[],
): TaskStatusTransition[] {
  if (!transitions) {
    return [];
  }

  return transitions
    .map((transition, index) => ({
      index,
      transition: normalizeTaskStatusTransition(transition),
    }))
    .sort((left, right) => {
      if (left.transition.at !== right.transition.at) {
        return left.transition.at - right.transition.at;
      }
      return left.index - right.index;
    })
    .map(({ transition }) => transition);
}

export function normalizeTaskNode(task: TaskNodeLike): TaskNode {
  return {
    ...task,
    status: normalizeTaskStatus(task.status),
    statusTransitions: normalizeTaskStatusTransitions(task.statusTransitions),
  };
}

export function isTerminalTaskStatus(status: CompatibleTaskStatus): boolean {
  const normalized = normalizeTaskStatus(status);
  return normalized === "completed" || normalized === "cancelled";
}

// 合法状态转换表
const VALID_TRANSITIONS: Record<TaskStatus, TaskStatus[]> = {
  pending: ["in_progress"],
  in_progress: ["suspended", "completed", "cancelled"],
  suspended: ["in_progress", "completed", "cancelled"],
  completed: [],
  cancelled: [],
};

/** 检查状态转换是否合法 */
export function canTransition(from: TaskStatus, to: TaskStatus): boolean {
  return VALID_TRANSITIONS[from].includes(to);
}

function createTaskTransitionId(
  taskId: string,
  reason: TaskTransitionReason,
  toStatus: TaskStatus,
  at: number,
  sequence: number,
): string {
  if (reason === "task.create") {
    return `${taskId}:task.create:${at}`;
  }
  return `${taskId}:${reason}:${toStatus}:${at}:${sequence}:${createUuidV4()}`;
}

export function buildInitialTaskStatusTransition(
  taskId: string,
  at: number,
): TaskStatusTransition {
  return {
    id: createTaskTransitionId(taskId, "task.create", "pending", at, 0),
    at,
    fromStatus: null,
    toStatus: "pending",
    reason: "task.create",
  };
}

export interface TaskTransitionOptions {
  at?: number;
  reason?: TaskTransitionReason;
  actorId?: string;
  sourceHostId?: string;
  operationId?: string;
  relatedTimeBlockId?: string;
  relatedTimeBlockTransitionRef?: string;
  autoGenerated?: boolean;
}

/**
 * 执行状态转换，返回新的 TaskNode（不可变）。
 * 非法转换时抛出 Error。
 * 转换到 completed / cancelled 时同时设置 completedAt。
 */
export function transition(
  task: TaskNodeLike,
  to: TaskStatus,
  options: TaskTransitionOptions = {},
): TaskNode {
  const normalizedTask = normalizeTaskNode(task);
  const existingTransitions = normalizedTask.statusTransitions ?? [];
  if (!canTransition(normalizedTask.status, to)) {
    throw new Error(`Invalid transition: ${normalizedTask.status} → ${to}`);
  }
  const requestedAt = options.at ?? Date.now();
  const lastTransitionAt =
    existingTransitions[existingTransitions.length - 1]?.at ??
    normalizedTask.createdAt;
  const at = Math.max(requestedAt, lastTransitionAt + 1);
  const nextTransitions = [
    ...existingTransitions,
    {
      id: createTaskTransitionId(
        normalizedTask.id,
        options.reason ?? "task.transition",
        to,
        at,
        existingTransitions.length,
      ),
      at,
      fromStatus: normalizedTask.status,
      toStatus: to,
      reason: options.reason ?? "task.transition",
      ...(options.actorId !== undefined ? { actorId: options.actorId } : {}),
      ...(options.sourceHostId !== undefined
        ? { sourceHostId: options.sourceHostId }
        : {}),
      ...(options.operationId !== undefined
        ? { operationId: options.operationId }
        : {}),
      ...(options.relatedTimeBlockId !== undefined
        ? { relatedTimeBlockId: options.relatedTimeBlockId }
        : {}),
      ...(options.relatedTimeBlockTransitionRef !== undefined
        ? {
            relatedTimeBlockTransitionRef:
              options.relatedTimeBlockTransitionRef,
          }
        : {}),
      ...(options.autoGenerated !== undefined
        ? { autoGenerated: options.autoGenerated }
        : {}),
    } satisfies TaskStatusTransition,
  ];
  return {
    ...normalizedTask,
    status: to,
    updatedAt: at,
    statusTransitions: nextTransitions,
    ...(to === "completed" || to === "cancelled" ? { completedAt: at } : {}),
  };
}
